### ISSUE TITLE
Reorganise the directory structure

### ISSUE THREAD

**Issue by koffie** [isogeny-primes/quadratic-torsion#7]
Right now there is no coherent directory structure. I propose the following structure:

- granville - a merger of the `graphs` and `granville_constants` directories, containing all the code for doing the comparison with granvilles conjecture
- magma_scripts - a directory that contains all the .m files
- logs - a directory that contains the logs of executing all the different .m files
- positive_rank_lists - the contents of the `genus_one_lists` directory together with the positive rank lists of genus 2
- python_scripts - a rename of the `quadratic_torsion` directory

**Comment by BarinderBanwait** [comment]
I agree that the above would be an improvement to the directory structure, and am aware that it is currently less than ideal; I suppose that was due to the tight ANTS deadline we had to get things done for.

I'm happy for this to be addressed before the next June 10th deadline, once the open PRs are merged.

**Comment by BarinderBanwait** [comment]
Done and merged in #14
